import{structuredResponse}from"@/lib/ai/deepseek";import type{MasterProfile,MatchAnalysis,ResumeDirection,ResumeStrategy,SelectedResumeItems,StructuredJob,TargetedResumeContent}from"@/types/job";import type{ResumeRecord}from"@/types/resume";
const schema={type:"object",additionalProperties:false,required:["summary","rewrites","section_order","skills_order"],properties:{summary:{type:"string"},rewrites:{type:"array",items:{type:"object",additionalProperties:false,required:["record_id","targeted_title","points"],properties:{record_id:{type:"string"},targeted_title:{type:"string"},points:{type:"array",minItems:2,maxItems:2,items:{type:"string"}}}}},section_order:{type:"array",items:{type:"string"}},skills_order:{type:"array",items:{type:"string"}}}};
type AiResume={summary:string;rewrites:Array<{record_id:string;targeted_title:string;points:string[]}>;section_order:string[];skills_order:string[]};
const selectedRecords=(profile:MasterProfile,selected:SelectedResumeItems)=>[...profile.experiences.filter(x=>selected.experiences.includes(x.id)),...profile.projects.filter(x=>selected.projects.includes(x.id)),...profile.research.filter(x=>selected.research.includes(x.id)),...profile.publications.filter(x=>selected.publications.includes(x.id))];
const editable=(item:ResumeRecord)=>{const raw=item.description??item.highlights??item.results??"";return Array.isArray(raw)?raw.map(String).join("；"):String(raw)};
const recordTitle=(item:ResumeRecord)=>String(item.company??item.title_cn??item.title??item.name??"");
const quantitativeEvidence=(records:ResumeRecord[])=>records.map(item=>{
 const evidence=Object.entries(item).flatMap(([field,value])=>{if(value==null)return[];if(Array.isArray(value))return[{field,value:value.map(String).join("；"),listed_item_count:value.length}];const text=String(value);return /\d|%|万|千|百|余|多|场|篇|人|页|项|个|次|粉丝|浏览|阅读/.test(text)?[{field,value:text}]:[]});
 return{record_id:item.id,evidence};
});
const strategies:Record<Exclude<ResumeDirection,"auto">,ResumeStrategy>={
 product_manager:{direction:"product_manager",label:"产品经理",positioning:"将跨学科研究、用户洞察、数据分析、AI工作流与从0到1交付整合为产品能力",writing_focus:["用户/业务问题与目标","调研、需求拆解与优先级","跨团队协作与方案决策","上线、验证、效率或影响结果"],section_order:["profile","skills","experience","projects","research","education","awards","publications"]},
 landscape_designer:{direction:"landscape_designer",label:"景观设计师",positioning:"突出场地理解、设计策略、技术表达、协同推进与落地能力",writing_focus:["项目尺度与场地约束","调研分析和概念策略","图纸、模型、可视化及软件","方案深化、协同、施工或空间生态成效"],section_order:["profile","education","experience","projects","skills","research","awards","publications"]},
 research_academic:{direction:"research_academic",label:"科研/教职",positioning:"突出研究问题、方法、数据、论文产出与教学传播能力",writing_focus:["研究问题与理论背景","方法、样本、数据和工具","独立贡献与协作职责","论文、平台、发现或学术影响"],section_order:["profile","education","research","publications","projects","experience","skills","awards"]},
 content_media:{direction:"content_media",label:"内容与新媒体",positioning:"突出选题洞察、跨平台内容生产、视觉叙事、运营与传播效果",writing_focus:["目标受众和传播目标","选题、策划与内容生产流程","平台组合、视觉和视频表达","触达、互动、增长或运营沉淀"],section_order:["profile","skills","experience","projects","research","education","awards","publications"]},
};
function inferDirection(jd:StructuredJob,requested:ResumeDirection):Exclude<ResumeDirection,"auto">{if(requested!=="auto")return requested;const text=[jd.job_title,...jd.keywords,...jd.skills,...jd.core_requirements].join(" ").toLowerCase();if(/景观|园林|空间|建筑|landscape|设计师/.test(text))return"landscape_designer";if(/研究|教职|博士|科研|research|academic|讲师/.test(text))return"research_academic";if(/内容|新媒体|运营|编辑|传播|content|media/.test(text))return"content_media";return"product_manager";}
export async function generateResume(profile:MasterProfile,jd:StructuredJob,match:MatchAnalysis,selected:SelectedResumeItems,requested:ResumeDirection="auto"):Promise<TargetedResumeContent>{const records=selectedRecords(profile,selected),strategy=strategies[inferDirection(jd,requested)];const fallbackRewrites=records.map(item=>({record_id:item.id,original:editable(item),targeted:editable(item),accepted:false,original_title:recordTitle(item),targeted_title:recordTitle(item)}));const context={profile:profile.profile,education:profile.education,selected_records:records,skills:profile.skills,publications:profile.publications,awards:profile.awards,quantitative_evidence:quantitativeEvidence(records),database_counts:{education:profile.education.length,experiences:profile.experiences.length,projects:profile.projects.length,research:profile.research.length,publications:profile.publications.length,skills:profile.skills.length,awards:profile.awards.length}};
 const instructions=`你是资深中文简历顾问，当前简历方向为“${strategy.label}”。职业定位：${strategy.positioning}。写作重点：${strategy.writing_focus.join("；")}。
根据JD重新组织职业叙事，不使用同一套话术处理所有岗位。整份简历必须以一张A4为内容预算。summary控制在90至130个中文字符、最多3句，只保留目标定位、2项最强证据和岗位价值；内容具体、可扫描，不堆砌形容词。
每一条工作、项目或科研经历必须输出且只输出2个points，不得输出一段概述。每个point控制在45至75个中文字符，采用图片参考中的“能力标签：完整STAR内容”写法（JSON中用普通文字，不使用Markdown星号），例如“需求洞察与方案设计：针对……问题，分析……并设计……，形成/实现……结果”。第一点优先写需求、分析和方案；第二点优先写推动、验证、运营或结果。每一点内部必须同时出现任务背景、个人动作、方法和真实结果，不能只把原文换一种说法。只保留与JD最相关的方法、动作和一个关键结果，删除过程性赘述。使用“识别、拆解、分析、设计、搭建、推动、验证、优化”等强动词，不使用S/T/A/R字母标签。
targeted_title也必须改写：保留真实项目/组织名称，补充产品对象或核心成果，用“项目名｜产品对象/核心能力”或“公司名｜岗位方向”的短标题；不得把研究项目伪装成任职经历，不得虚构职位。
量化必须证据可追溯。优先使用quantitative_evidence中的原始数字；允许根据资料库明确列出的项目、模块、平台、活动、文章、页面、样本或时间范围进行计数、求和、差值和百分比计算，但计算所需的每个原始值都必须存在于同一条记录或明确关联的资料中。可以把“列出4个模块”归纳为“完成4个模块”，可以根据明确起止值计算增长率；不得把database_counts当成单个项目的成果，也不得由职责、形容词或行业常识推测用户量、效率、转化率、收入和影响。无法验证时使用定性结果，不补造数字。
产品经理方向强调用户/业务问题、需求拆解、优先级、协作、决策、交付和验证；景观设计方向强调场地条件、设计策略、技术图纸/模型/可视化、专业协同和落地效果；科研方向强调问题、方法、数据、贡献和成果；内容方向强调受众、选题、生产、平台运营和传播成效。
避免“负责、参与、熟悉、具备”等空泛开头。只可解释既有事实及其与岗位的关系；严禁虚构经历、职责、工具、成果、数字、客户、组织或时间。不得改变专有名称、日期、学历、论文、技能和奖项。record_id必须来自输入。section_order优先使用给定策略顺序，仅在JD有充分理由时调整。只返回Schema规定的JSON。`;
 const ai=await structuredResponse<AiResume>("targeted_resume",schema,instructions,JSON.stringify({jd,match,resume_strategy:strategy,master_profile:context}));if(!ai)throw new Error("AI未返回有效的STAR改写，请检查DeepSeek配置后重试");const validIds=new Set(records.map(x=>x.id));const valid=new Map(ai.rewrites.filter(x=>validIds.has(x.record_id)&&x.points.length===2&&x.points.every(Boolean)).map(x=>[x.record_id,{record_id:x.record_id,original:editable(records.find(r=>r.id===x.record_id)!),targeted:x.points.map(point=>`• ${point.replace(/^[-•]\s*/,"")}`).join("\n"),accepted:false,original_title:recordTitle(records.find(r=>r.id===x.record_id)!),targeted_title:x.targeted_title.trim()||recordTitle(records.find(r=>r.id===x.record_id)!)}]));const missing=records.filter(x=>!valid.has(x.id));if(missing.length)throw new Error(`AI改写不完整：${missing.length}条经历未生成两点STAR内容，请重试`);const allowed=new Set(strategy.section_order);const order=[...ai.section_order.filter(x=>allowed.has(x)),...strategy.section_order.filter(x=>!ai.section_order.includes(x))];return{summary:ai.summary,section_order:order,skills_order:ai.skills_order,rewrites:fallbackRewrites.map(x=>valid.get(x.record_id)!),selected,strategy};}
