"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import type { Profile } from "@/types/resume";

const initial:Profile={id:"00000000-0000-0000-0000-000000000001",name_cn:"",name_en:"",job_title:"",phone:"",email:"",city:"",website:"",github:"",linkedin:"",summary:"",avatar_url:""};
const fields:[keyof Profile,string,boolean?][]=[["name_cn","中文姓名"],["name_en","英文姓名"],["job_title","目标方向"],["phone","电话"],["email","邮箱"],["city","城市"],["website","个人网站"],["github","GitHub"],["linkedin","LinkedIn"],["summary","个人简介",true]];
export default function Page(){const [profile,setProfile]=useState(initial);const [message,setMessage]=useState("");const [avatarFile,setAvatarFile]=useState<File|null>(null);const [uploading,setUploading]=useState(false);
 useEffect(()=>{void supabase.from("profile").select("*").limit(1).maybeSingle().then(({data,error})=>{if(data)setProfile(data as Profile);if(error)setMessage(error.message)})},[]);
 async function save(){const {error}=await supabase.from("profile").upsert({...profile,updated_at:new Date().toISOString()});setMessage(error?.message??"已保存")}
 async function uploadAvatar(){if(!avatarFile)return;setUploading(true);setMessage("");try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("请先登录后台");const extension=avatarFile.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${user.id}/profile.${extension}`;const {error:uploadError}=await supabase.storage.from("avatars").upload(path,avatarFile,{upsert:true,contentType:avatarFile.type});if(uploadError)throw uploadError;const {data:{publicUrl}}=supabase.storage.from("avatars").getPublicUrl(path);const avatarUrl=`${publicUrl}?v=${Date.now()}`;const next={...profile,avatar_url:avatarUrl};const {error:saveError}=await supabase.from("profile").upsert({...next,updated_at:new Date().toISOString()});if(saveError)throw saveError;setProfile(next);setAvatarFile(null);setMessage("头像已上传并保存")}catch(error){setMessage(error instanceof Error?error.message:"头像上传失败")}finally{setUploading(false)}}
 return <section className="mx-auto max-w-3xl"><p className="text-xs uppercase tracking-[.2em] text-neutral-500">Master profile</p><h1 className="mb-10 mt-2 border-b border-neutral-300 pb-5 text-4xl font-light">基本资料</h1>{message&&<p className="mb-5">{message}</p>}<div className="mb-8 grid gap-6 border-b border-neutral-300 pb-8 md:grid-cols-[120px_1fr]">{profile.avatar_url?<img src={profile.avatar_url} alt="当前头像" className="h-28 w-28 rounded-full object-cover object-center"/>:<div className="flex h-28 w-28 items-center justify-center rounded-full bg-neutral-200 text-xs text-neutral-500">暂无头像</div>}<div><label><span className="mb-2 block text-xs text-neutral-500">上传头像</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>setAvatarFile(event.target.files?.[0]??null)} className="block w-full border border-neutral-300 bg-white p-3"/></label><p className="mt-2 text-xs text-neutral-500">支持 JPG、PNG、WebP，最大 5MB。头像按中心位置裁切为圆形。</p><button onClick={uploadAvatar} disabled={!avatarFile||uploading} className="mt-4 bg-black px-5 py-3 text-white disabled:opacity-40">{uploading?"上传中…":"上传并保存头像"}</button></div></div><div className="grid gap-5 md:grid-cols-2">{fields.map(([key,label,long])=><label key={key} className={long?"md:col-span-2":""}><span className="mb-2 block text-xs text-neutral-500">{label}</span>{long?<textarea className="min-h-40 w-full border border-neutral-300 bg-white p-3" value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})}/>:<input className="w-full border border-neutral-300 bg-white p-3" value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})}/>}</label>)}</div><button onClick={save} className="mt-8 bg-black px-8 py-4 text-white">保存基本资料</button></section>}
