import{importJob}from"./api/jobAgent.js";import type{Extraction,JobCandidate,JobObject}from"./types/job.js";
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id)as T;const fields=["company_name","job_title","location","salary","job_description"]as const;let current:JobObject|null=null;let visibleCandidates:JobCandidate[]=[];
let currentApplication:any=null;let assistantBase="",assistantToken="";
async function send(tabId:number,type:string){try{return await chrome.tabs.sendMessage(tabId,{type})}catch{await chrome.scripting.executeScript({target:{tabId},files:["content.js"]});return chrome.tabs.sendMessage(tabId,{type})}}
async function settings(){const saved=await chrome.storage.local.get(["base_url","token"]);const base=typeof saved.base_url==="string"?saved.base_url:"http://localhost:3000";const token=typeof saved.token==="string"?saved.token:"";$<HTMLInputElement>("base_url").value=base;$<HTMLInputElement>("token").value=token;return{base,token}}
async function loadAssistant(){const{base,token}=await settings();assistantBase=base.replace(/\/$/,"");assistantToken=token;const[tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab.url||!token||!tab.url.includes("zhipin.com/job_detail"))return;try{const response=await fetch(`${assistantBase}/api/applications/lookup?source_url=${encodeURIComponent(tab.url)}`,{headers:{Authorization:`Bearer ${token}`}});const result=await response.json();if(!response.ok||!result.found)return;currentApplication=result.application;if(!currentApplication)return;$<HTMLElement>("assistant").hidden=false;$("application_info").textContent=`Match ${result.match_score??"—"}% · Resume ${currentApplication.resume_version_id?"Ready":"Missing"} · Greeting ${currentApplication.greeting_text?"Ready":"Missing"} · ${currentApplication.application_status}`;}catch{/* 保留现有导入流程 */}}
$<HTMLButtonElement>("copy_greeting").addEventListener("click",async()=>{if(!currentApplication?.greeting_text)return fail("尚未准备招呼语");await navigator.clipboard.writeText(currentApplication.greeting_text);$("status").textContent="招呼语已复制，请在 BOSS 中确认后发送。"});
$<HTMLButtonElement>("open_resume").addEventListener("click",()=>{if(!currentApplication?.resume_version_id)return fail("尚未准备简历");void chrome.tabs.create({url:`${assistantBase}/resumes/${currentApplication.resume_version_id}`})});
$<HTMLButtonElement>("mark_sent").addEventListener("click",async()=>{if(!currentApplication)return;const response=await fetch(`${assistantBase}/api/applications/${currentApplication.id}/sent`,{method:"POST",headers:{Authorization:`Bearer ${assistantToken}`}});const result=await response.json();if(!response.ok)return fail(result.error||"记录失败");currentApplication=result.application;$("application_info").textContent=`Match ${currentApplication.match_score_snapshot??"—"}% · Sent`;$("status").textContent=result.duplicate?"该岗位已记录为已投递":"已记录投递时间与快照"});
async function init(){const{base}=await settings();$<HTMLAnchorElement>("open").href=`${base.replace(/\/$/,"")}/jobs`;const[tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab.id)return fail("无法读取当前标签页");if(tab.url?.includes("/web/geek/job")){const response=await send(tab.id,"EXTRACT_CANDIDATES")as{ok:boolean;candidates?:JobCandidate[]};visibleCandidates=response.candidates??[];$("title").textContent="搜索结果批量采集";$("company").textContent=`当前屏幕识别 ${visibleCandidates.length} 条岗位`;$<HTMLElement>("detail_fields").hidden=true;$<HTMLButtonElement>("save").hidden=true;$<HTMLButtonElement>("batch").hidden=false;const stored=await chrome.storage.local.get("batch_status");if(stored.batch_status)showProgress(stored.batch_status);return}try{const response=await send(tab.id,"EXTRACT_JOB")as{ok:boolean;extraction?:Extraction;error?:string};if(!response.ok||!response.extraction)return fail(response.error||"无法读取当前岗位");current=response.extraction.job;fields.forEach(key=>$<HTMLInputElement|HTMLTextAreaElement>(key).value=current![key]);$("title").textContent=current.job_title||"请确认岗位";$("company").textContent=`${current.company_name} · ${current.salary}`;$("warning").hidden=!response.extraction.needs_confirmation}catch(error){fail(error instanceof Error?error.message:"无法读取当前岗位")}}
function fail(message:string){$("status").textContent=message;$("title").textContent="读取失败"}function showProgress(value:any){if(value.running)$("status").textContent=`正在处理 ${value.index}/${value.total}：${value.title}，已保存 ${value.saved}`;else if(value.complete)$("status").textContent=`完成：已保存并分析 ${value.saved} 条岗位`;else if(value.stopped)$("status").textContent=`已停止：${value.error}（已保存 ${value.saved} 条）`}
$("save").addEventListener("click",async()=>{if(!current)return fail("没有岗位数据");fields.forEach(key=>current![key]=$<HTMLInputElement|HTMLTextAreaElement>(key).value.trim());const base=$<HTMLInputElement>("base_url").value.trim(),token=$<HTMLInputElement>("token").value.trim();if(!base||!token)return fail("请填写 URL 和 Import Token");await chrome.storage.local.set({base_url:base,token});$("status").textContent="正在保存并分析…";try{const result=await importJob(base,token,current);$("status").textContent=`${result.duplicate?"Already saved":"✓ Saved"} · Match ${result.match_score}% · ${result.recommendation}`;$<HTMLAnchorElement>("open").href=`${base.replace(/\/$/,"")}/jobs/${result.job_id}`}catch(error){fail(error instanceof Error?error.message:"导入失败")}});
$("batch").addEventListener("click",async()=>{const base=$<HTMLInputElement>("base_url").value.trim(),token=$<HTMLInputElement>("token").value.trim();if(!base||!token)return fail("请填写 URL 和 Import Token");if(!visibleCandidates.length)return fail("当前屏幕没有可采集的岗位卡片");await chrome.storage.local.set({base_url:base,token});$("status").textContent="正在按偏好预筛…";const response=await fetch(`${base.replace(/\/$/,"")}/api/jobs/candidates`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({candidates:visibleCandidates})});const result=await response.json();if(!response.ok)return fail(result.error||"预筛失败");const started=await chrome.runtime.sendMessage({type:"START_BATCH",candidates:result.candidates,base,token});if(!started?.ok)return fail(started?.error||"无法启动批量任务");$("status").textContent=`已启动，依次处理 ${result.candidates.length} 条岗位`});
chrome.runtime.onMessage.addListener(message=>{if(message?.type==="BATCH_PROGRESS")showProgress(message)});void init();void loadAssistant();
