"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";
import type { Job, JobCategory } from "@/types/job";

const categories: Array<["all" | JobCategory, string]> = [["all", "ALL"], ["priority", "PRIORITY"], ["recommended", "RECOMMENDED"], ["consider", "CONSIDER"], ["skip", "SKIP"]];
const categoryLabel: Record<JobCategory, string> = { priority: "Priority", recommended: "Recommended", consider: "Consider", skip: "Skip" };
const captured = (date: string) => { const days = Math.floor((Date.now() - new Date(date).getTime()) / 86400000); return days <= 0 ? "Today" : days === 1 ? "Yesterday" : `${days} days ago`; };

export default function JobsPage() {
  const [jobs, setJobs] = useState<Job[]>([]); const [resumeJobs, setResumeJobs] = useState(new Set<string>()); const [category, setCategory] = useState<"all" | JobCategory>("all"); const [sort, setSort] = useState("score"); const [location, setLocation] = useState(""); const [role, setRole] = useState(""); const [source, setSource] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function load() { const [jobResult, resumeResult] = await Promise.all([supabase.from("jobs").select("*").order("captured_at", { ascending: false }), supabase.from("resume_versions").select("job_id")]); setJobs((jobResult.data ?? []) as Job[]); setResumeJobs(new Set((resumeResult.data ?? []).map(row => row.job_id).filter(Boolean))); }
  useEffect(() => { let active = true; void Promise.all([supabase.from("jobs").select("*").order("captured_at", { ascending: false }), supabase.from("resume_versions").select("job_id")]).then(([jobResult, resumeResult]) => { if (!active) return; setJobs((jobResult.data ?? []) as Job[]); setResumeJobs(new Set((resumeResult.data ?? []).map(row => row.job_id).filter(Boolean))); }); return () => { active = false; }; }, []);
  const filtered = useMemo(() => jobs.filter(job => (category === "all" || job.category === category) && (!location || job.location.includes(location)) && (!role || job.job_title.toLowerCase().includes(role.toLowerCase())) && (!source || job.source === source)).sort((a, b) => sort === "captured" ? +new Date(b.captured_at) - +new Date(a.captured_at) : sort === "company" ? a.company_name.localeCompare(b.company_name) : sort === "salary" ? b.salary.localeCompare(a.salary) : (b.match_score ?? -1) - (a.match_score ?? -1)), [jobs, category, location, role, source, sort]);
  async function analyzeUnprocessed() { setBusy(true); const { data: { session } } = await supabase.auth.getSession(); const response = await fetch("/api/jobs/analyze-unprocessed", { method: "POST", headers: { Authorization: `Bearer ${session?.access_token}` } }); const result = await response.json(); setMessage(response.ok ? `已处理 ${result.processed} 个岗位` : result.error); await load(); setBusy(false); }
  return <main className="mx-auto min-h-screen max-w-7xl px-6 py-14"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-black pb-6"><div><p className="text-xs tracking-[.25em]">JOB AGENT</p><h1 className="mt-2 text-5xl font-light">岗位智能筛选</h1></div><div className="flex gap-3"><button onClick={analyzeUnprocessed} disabled={busy} className="border border-black px-5 py-3">{busy ? "分析中…" : "分析未处理岗位"}</button><Link href="/settings/jobs" className="border border-black px-5 py-3">筛选偏好</Link><Link href="/jobs/new" className="bg-black px-5 py-3 text-white">手动添加</Link></div></header><div className="mt-8 grid grid-cols-2 gap-px bg-neutral-300 md:grid-cols-5">{categories.map(([key, label]) => <button key={key} onClick={() => setCategory(key)} className={`p-5 text-left ${category === key ? "bg-black text-white" : "bg-white"}`}><span className="text-xs tracking-[.15em]">{label}</span><b className="mt-2 block text-3xl">{key === "all" ? jobs.length : jobs.filter(job => job.category === key).length}</b></button>)}</div><div className="mt-6 grid gap-3 md:grid-cols-4"><input className="border bg-white p-3" placeholder="地点" value={location} onChange={event => setLocation(event.target.value)} /><input className="border bg-white p-3" placeholder="岗位关键词" value={role} onChange={event => setRole(event.target.value)} /><select className="border bg-white p-3" value={source} onChange={event => setSource(event.target.value)}><option value="">全部来源</option><option value="boss">BOSS</option><option value="manual">手动</option></select><select className="border bg-white p-3" value={sort} onChange={event => setSort(event.target.value)}><option value="score">匹配分数</option><option value="captured">采集日期</option><option value="salary">薪资</option><option value="company">公司</option></select></div>{message && <p className="mt-4">{message}</p>}<div className="mt-7 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead><tr className="border-b text-neutral-500"><th className="py-3">Company</th><th>Role</th><th>Location</th><th>Salary</th><th>Match</th><th>Category</th><th>Resume</th><th>Status</th><th>Captured</th></tr></thead><tbody>{filtered.map(job => <tr key={job.id} className="border-b border-neutral-200"><td className="py-5">{job.company_name}</td><td><Link className="font-medium" href={`/jobs/${job.id}`}>{job.job_title}</Link></td><td>{job.location}</td><td>{job.salary}</td><td className="font-medium">{job.match_score == null ? "—" : `${job.match_score}%`}</td><td>{categoryLabel[job.category] ?? job.category}</td><td>{resumeJobs.has(job.id) ? "✓" : job.category === "priority" ? <Link href={`/jobs/${job.id}`}>Generate</Link> : "—"}</td><td>{job.status}</td><td>{captured(job.captured_at || job.created_at)}</td></tr>)}</tbody></table>{filtered.length === 0 && <p className="py-16 text-center text-neutral-500">没有符合当前筛选条件的岗位。</p>}</div></main>;
}
